wm.weapon.axe=Топор
wm.weapon.baseball_bat=Бейбольная бита
wm.weapon.bottle=Бутылка
wm.weapon.bottle_broken=Розочка
wm.weapon.cleaver=Нож мясника
wm.weapon.combat_knife=Боевой нож
wm.weapon.crowbar=Монтировка
wm.weapon.fireaxe=Пожарный топор
wm.weapon.fists=Кулаки
wm.weapon.fork=Вилка
wm.weapon.fubar=Монтировка-гвоздодёр
wm.weapon.hammer=Молоток
wm.weapon.ice_axe=Ледоруб
wm.weapon.katana=Катана
wm.weapon.keyboard=Клавиатура
wm.weapon.kitchen_knife=Кухонный нож
wm.weapon.mace=Моргенштерн
wm.weapon.machete=Мачете
wm.weapon.modern_sword=Современный меч
wm.weapon.pickaxe=Кирка
wm.weapon.pipe=Труба
wm.weapon.pitchfork=Вилы
wm.weapon.police_baton=Полицейская дубинка
wm.weapon.screwdriver=Отвёртка
wm.weapon.shield=Щит
wm.weapon.shovel=Лопата
wm.weapon.sickle=Серп
wm.weapon.sledge=Кувалда
wm.weapon.soldier_shovel=Саперская лопата
wm.weapon.stunstick=Электрошокер
wm.weapon.wrench=Развадной ключ
wm.weapon.razor=Бритва
wm.weapon.rock=Камень
wm.weapon.rpg_missile=РПГ снаряд