AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.axe",
		Icon = "icons/wm_axe.png",
		SelectionIcon = "icons/wm_axe_i.png",
		KillIcon = "icons/wm_axe_k.png",
		Material = MAT_METAL,
		VModel = "models/wm/axe/v.mdl",
		VModelPos = Vector(-6,-4.5,1.5),
		VModelRot = Angle(5,5,-1),
		FOV = 80,
		WModel = "models/wm/axe/w.mdl",
		Hold = "melee",
		Rays = {{Angle(-20,-5,0),0},{Angle(0,0,0),0.05},{Angle(20,5,0),0.05}},
		RaysDetails = 4,
		OnlyOneRay = true,
		WModelPos = Vector(3.4, -1, -3),
		WModelRot = Angle(180, 150, 10),
		AnimationHit = {"Attack_Quick"},
		AnimationDraw = "Draw",
		AnimationIdle = "Idle",
		AttackWait = Vector(1,-25,0),
		AttackHitWait = 0.3,
		AttackDistance = 50,
		Damage = Vector(20,40),
		DamageProp = Vector(30,40),
		IdleScale = 0.5,
		PunchAngle = Angle(10,0,0),
		SwingSounds = WMLib.SoundsSwing["LightSharp"],
		BlockPos = Vector(0,10,0),
		BlockRot = Angle(0,0,-30),
		WBlockPos = Vector(0,-3,0),
		WBlockRot = Angle(0,30,-45),
		BlockWait = 1,
		BlockPower = 0.5,
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end