AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.bottle_broken",
		Icon = "icons/wm_bottle_broken.png",
		SelectionIcon = "icons/wm_bottle_broken_i.png",
		KillIcon = "icons/wm_bottle_broken_k.png",
		Hide = true,
		Material = MAT_GLASS,
		Sharp = true,
		VModel = "models/wm/combat_knife/v.mdl",
		VModelPos = Vector(1,2,-1),
		VModelRot = Angle(0,-5,-10),
		VModelBones = {["tag_weapon"] = {Vector(0,0,0),Angle(0,0,0),Vector(0,0,0),false}},
		VModelElements = {{"models/wm/bottle_broken/w.mdl","ValveBiped.Bip01_R_Hand",Vector(2.75,-1.4,0),Angle(0,0,180),Vector(0.5,0.8,0.5)}},
		FOV = 75,
		WModel = "models/wm/bottle_broken/w.mdl",
		Hold = "knife",
		Rays = {{Angle(10,0,0),0},{Angle(5,-5,0),0},{Angle(10,0,0),0},{Angle(15,5,0),0},{Angle(10,0,0),0},{Angle(15,-5,0),0},{Angle(10,0,0),0},{Angle(5,5,0),0}},
		RaysDetails = 3,
		OnlyOneRay = true,
		WModelPos = Vector(2.5, -0.75, 0.5),
		WModelRot = Angle(200, 160, 0),
		WModelSize = Vector(0.5,0.8,0.5),
		AnimationHit = {"H1_Wpn_Melee_Bayonet_Knife_Stab"},
		AnimationIdle = "H1_Wpn_Melee_Bayonet_Knife_Idle",
		AnimationDraw = "H1_Wpn_Melee_Bayonet_Knife_Pullout",
		AttackWait = Vector(1,-50,0),
		AttackHitWait = 0,
		AttackDistance = 75,
		Damage = Vector(15,30),
		DamageProp = Vector(0,5),
		PunchAngle = Angle(3,0,0), 
		InertiaScale = 0.25,
		SwingSounds = WMLib.SoundsSwing["LightSharp"],
		BlockPos = Vector(0,4,3),
		BlockRot = Angle(0,0,-30),
		WBlockPos = Vector(0,0,0),
		WBlockRot = Angle(0,0,0),
		BlockHold = "fist",
		WaterSplashSize = 2.5,
		BlockWait = 1.5,
		BlockPower = 0.75
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end