AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.cleaver",
		Icon = "icons/wm_cleaver.png",
		SelectionIcon = "icons/wm_cleaver_i.png",
		KillIcon = "icons/wm_cleaver_k.png",
		Material = MAT_METAL,
		Sharp = true,
		VModel = "models/wm/cleaver/v.mdl",
		VModelPos = Vector(-4,3,-2),
		VModelRot = Angle(0,-5,-10),
		FOV = 75,
		WModel = "models/wm/cleaver/w.mdl",
		Hold = "melee",
		Rays = {{Angle(-20,-20,0),0},{Angle(0,0,0),0.05},{Angle(20,20,0),0.05}},
		RaysDetails = 4,
		OnlyOneRay = true,
		WModelPos = Vector(1.2, 1.1, 0.9),
		WModelRot = Angle(190, 150, 0),
		AnimationHit = {"Attack_Quick"},
		AnimationDraw = "Draw",
		AnimationIdle = "Idle",
		AttackWait = Vector(0.5,0,30),
		AttackHitWait = 0.3,
		Damage = Vector(10,25),
		DamageProp = Vector(0,1),
		KickScale = 0.25,
		AttackDistance = 50,
		PunchAngle = Angle(0,5,0),
		InertiaScale = 0.5,
		SwingSounds = WMLib.SoundsSwing["LightSharp"],
		BlockPos = Vector(0,7,-5),
		BlockRot = Angle(0,0,-30),
		WBlockPos = Vector(2,0,-4),
		WBlockRot = Angle(90,-90,-30),
		BlockHold = "camera",
		BlockWait = 1,
		BlockPower = 0.5,
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end