AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.fork",
		Icon = "icons/wm_fork.png",
		SelectionIcon = "icons/wm_fork_i.png",
		KillIcon = "icons/wm_fork_k.png",
		Material = MAT_METAL,
		Sharp = true,
		Funny = true,
		VModel = "models/wm/combat_knife/v.mdl",
		VModelPos = Vector(1,2,-1),
		VModelRot = Angle(0,-5,-10),
		VModelBones = {["tag_weapon"] = {Vector(0,0,0),Angle(0,0,0),Vector(0,0,0),false}},
		VModelElements = {{"models/wm/fork/w.mdl","ValveBiped.Bip01_R_Hand",Vector(5,-1.25,-3),Angle(-30,160,180),Vector(0.7,0.7,0.7)}},
		FOV = 75,
		WModel = "models/wm/fork/w.mdl",
		Hold = "knife",
		Rays = {{Angle(0,0,0),0},{Angle(-5,-5,0),0},{Angle(0,0,0),0},{Angle(5,5,0),0},{Angle(0,0,0),0},{Angle(5,-5,0),0},{Angle(0,0,0),0},{Angle(-5,5,0),0}},
		RaysDetails = 2,
		OnlyOneRay = true,
		WModelPos = Vector(3,-2,-3),
		WModelRot = Angle(-90, -30, 180),
		WModelSize = Vector(0.7,0.7,0.7),
		AnimationHit = {"H1_Wpn_Melee_Bayonet_Knife_Stab"},
		AnimationDraw = "H1_Wpn_Melee_Bayonet_Knife_Pullout",
		AttackWait = Vector(0.5,-25,0),
		AttackHitWait = 0.2,
		AttackDistance = 50,
		Damage = Vector(15,25),
		DamageProp = Vector(0,1),
		PunchAngle = Angle(1,5,0),
		InertiaScale = 0.25,
		SwingSounds = WMLib.SoundsSwing["LightSharp"],
		KickScale = 0.5,
		BlockPos = Vector(0,5,2),
		BlockRot = Angle(0,-10,-30),
		WBlockPos = Vector(0,0,0),
		WBlockRot = Angle(0,0,0),
		BlockHold = "fist",
		BlockWait = 1.25,
		BlockPower = 0.8,
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end