AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.fireaxe",
		Icon = "icons/wm_fireaxe.png",
		SelectionIcon = "icons/wm_fireaxe_i.png",
		KillIcon = "icons/wm_fireaxe_k.png",
		Heavy = true,
		Material = MAT_WOOD,
		VModel = "models/wm/fireaxe/v.mdl",
		VModelPos = Vector(-4,0,-4),
		VModelRot = Angle(0,-5,5),
		FOV = 80,
		WModel = "models/wm/fireaxe/w.mdl",
		Hold = "melee2",
		Rays = {{Angle(-50,-10,0),0},{Angle(0,0,0),0.05},{Angle(50,10,0),0.05}},
		RaysDetails = 4,
		OnlyOneRay = true,
		WModelPos = Vector(3.2, -1.5, -2),
		WModelRot = Angle(180, 160, 0),
		AnimationHit = {"Attack_Charge_Begin"},
		AnimationHitEnd = "Attack_Charge_End",
		AnimationDraw = "Draw",
		AnimationIdle = "Idle",
		AttackWait = Vector(1,0,0),
		AttackHitWait = 0.3,
		AttackDistance = 60,
		Damage = Vector(30,60),
		DamageProp = Vector(40,60),
		IdleScale = 0.25,
		PunchAngle = Angle(20,2,0),
		InertiaScale = 2.5,
		SwingSounds = "empty",
		BlockPos = Vector(0,4,7),
		BlockRot = Angle(0,0,30),
		WBlockPos = Vector(0,0,0),
		WBlockRot = Angle(90,-90,-10),
		BlockHold = "camera",
		BlockWait = 0.5,
		BlockPower = 0.166,
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end