AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.fubar",
		Icon = "icons/wm_fubar.png",
		SelectionIcon = "icons/wm_fubar_i.png",
		KillIcon = "icons/wm_fubar_k.png",
		Material = MAT_METAL,
		VModel = "models/wm/fubar/v.mdl",
		VModelPos = Vector(-6,1,-2),
		VModelRot = Angle(0,-5,5),
		FOV = 80,
		WModel = "models/wm/fubar/w.mdl",
		Hold = "melee2",
		Rays = {{Angle(0,-50,0),0},{Angle(0,-25,0),0.025},{Angle(0,0,0),0.025},{Angle(0,25,0),0.025},{Angle(0,50,0),0.025}},
		RaysDetails = 4,
		WModelPos = Vector(1.5, 1, 0),
		WModelRot = Angle(185, 150, 0),
		AnimationHit = {"Attack_Quick"},
		AnimationDraw = "Draw",
		AnimationIdle = "Idle",
		AttackWait = Vector(1.5,0,50),
		AttackHitWait = 0.6,
		AttackDistance = 65,
		Damage = Vector(20,60),
		DamageProp = Vector(5,30),
		KickScale = 1.25,
		PunchAngle = Angle(0,20,0),
		InertiaScale = 2,
		SwingWait = 0.4,
		BlockPos = Vector(0,4,5),
		BlockRot = Angle(0,0,30),
		WBlockPos = Vector(5,-3,-5),
		WBlockRot = Angle(90,-90,-10),
		BlockHold = "camera",
		BlockWait = 0.5,
		BlockPower = 0.166,
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end