AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.modern_sword",
		Icon = "icons/wm_modern_sword.png",
		SelectionIcon = "icons/wm_modern_sword_i.png",
		KillIcon = "icons/wm_modern_sword_k.png",
		Material = MAT_METAL,
		Sharp = true,
		VModel = "models/wm/modern_sword/v.mdl",
		VModelPos = Vector(5, 1, -2),
		VModelRot = Angle(0,-5,0),
		FOV = 70,
		WModel = "models/wm/modern_sword/w.mdl",
		Hold = "melee2",
		Rays = {{Angle(-30,-5,0),0},{Angle(0,0,0),0},{Angle(30,5,0),0.015}},
		RaysDetails = 4,
		WModelPos = Vector(3, -1, 1.6),
		WModelRot = Angle(-5, -10, 180),
		AnimationHit = {"H1_Wpn_Melee_Gladius_Swipe"},
		AnimationDraw = "H1_Wpn_Melee_Gladius_Pullout",
		AnimationIdle = "H1_Wpn_Melee_Gladius_Idle",
		AnimationInspect = {"H1_Wpn_Melee_Gladius_Inspect"},
		AttackWait = Vector(1,-30,0),
		AttackHitWait = 0.05,
		Damage = Vector(20,35),
		DamageProp = Vector(5,15),
		PunchAngle = Angle(5,1,0),
		IdleScale = 0.5,
		AttackDistance = 80,
		BlockPos = Vector(0,1,-5),
		BlockRot = Angle(0,0,-30),
		WBlockPos = Vector(-1,0,0),
		WBlockRot = Angle(-30,30,-30),
		BlockHold = "knife",
		BlockWait = 1,
		BlockPower = 0.166,
		SwingSounds = {"weapons/l4d2_kf2_katana/katana_swing_miss1.wav","weapons/l4d2_kf2_katana/katana_swing_miss2.wav"},
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end