AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.pickaxe",
		Icon = "icons/wm_pickaxe.png",
		SelectionIcon = "icons/wm_pickaxe_i.png",
		KillIcon = "icons/wm_pickaxe_k.png",
		Heavy = true,
		Material = MAT_METAL,
		VModel = "models/wm/pickaxe/v.mdl",
		VModelPos = Vector(-7,2,-1),
		VModelRot = Angle(0,-5,-5),
		FOV = 80,
		WModel = "models/wm/pickaxe/w.mdl",
		Hold = "melee2",
		Rays = {{Angle(0,40,0),0},{Angle(0,0,0),0.05},{Angle(0,-40,0),0.05}},
		RaysDetails = 4,
		WModelPos = Vector(1, 0.5, 0),
		WModelRot = Angle(180, 160, 0),
		AnimationHit = {"Attack_Quick"},
		AnimationDraw = "Draw",
		AnimationIdle = "Idle",
		AttackWait = Vector(1,0,50),
		AttackHitWait = 0.3,
		AttackDistance = 80,
		Damage = Vector(15,50),
		DamageProp = Vector(25,35),
		IdleScale = 0.25,
		PunchAngle = Angle(0,-10,0),
		SwingWait = 0.2,
		BlockPos = Vector(7,-3,-20),
		BlockRot = Angle(-70,0,0),
		WBlockPos = Vector(5,0,-3),
		WBlockRot = Angle(45,-90,45),
		BlockHold = "knife",
		BlockWait = 0.75,
		BlockPower = 0.166,
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end