AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.pipe",
		Icon = "icons/wm_pipe.png",
		SelectionIcon = "icons/wm_pipe_i.png",
		KillIcon = "icons/wm_pipe_k.png",
		Material = MAT_METAL,
		VModel = "models/wm/pipe/v.mdl",
		VModelPos = Vector(-4,-3,-1.5),
		VModelRot = Angle(5,-5,-1),
		FOV = 80,
		WModel = "models/wm/pipe/w.mdl",
		Hold = "melee",
		Rays = {{Angle(0,20,0),0},{Angle(0,0,0),0.025},{Angle(0,-20,0),0.025}},
		RaysDetails = 4,
		OnlyOneRay = true,
		WModelPos = Vector(3, -1, -6.5),
		WModelRot = Angle(180, 1200, 0),
		AnimationHit = {"Attack_Quick"},
		HitSounds = {"phx/hmetal1.wav","phx/hmetal2.wav","phx/hmetal3.wav"},
		AnimationDraw = "Draw",
		AnimationIdle = "Idle",
		AttackWait = Vector(1,-10,25),
		AttackHitWait = 0.3,
		AttackDistance = 50,
		Damage = Vector(10,30),
		DamageProp = Vector(5,20),
		IdleScale = 0.5,
		PunchAngle = Angle(0,-10,0),
		SwingSounds = WMLib.SoundsSwing["Light"],
		BlockPos = Vector(0,10,0),
		BlockRot = Angle(0,0,-40),
		WBlockPos = Vector(1,-5,2),
		WBlockRot = Angle(30,30,-30),
		BlockWait = 1,
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end