AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.rock",
		CustomAuthor = "Haveaniceday.",
		SelectionIcon = "icons/wm_rock_i.png",
		KillIcon = "icons/wm_rock_k.png",
		Material = MAT_CONCRETE,
		Funny = true,
		Icon = "icons/wm_rock.png",
		VModel = "models/wm/rock/v.mdl",
		VModelPos = Vector(-1,1.5,-1),
		VModelRot = Angle(0,-5,5),
		FOV = 70,
		WModel = "models/wm/rock/w.mdl",
		Hold = "melee",
		Rays = {{Angle(5,0,0),0},{Angle(17.5,0,0),0},{Angle(30,0,0),0}},
		RaysDetails = 3,
		OnlyOneRay = true,
		WModelPos = Vector(2, -5, 0),
		WModelRot = Angle(180, 0, 0),
		AnimationHit = {"Slash"},
		AnimationIdle = "Idle",
		AttackWait = Vector(2,-50,0),
		AttackHitWait = 0.65,
		Damage = Vector(20,50),
		DamageProp = Vector(0,30),
		PunchAngle = Angle(20,0,0),
		AttackDistance = 60,
		SwingWait = 0.4,
		BlockPos = Vector(2,2,-15),
		BlockRot = Angle(-60,0,0),
		WBlockPos = Vector(0,0,0),
		WBlockRot = Angle(0,0,0),
		BlockHold = "camera",
		BlockWait = 0.5,
		BlockPower = 0.5,
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end