AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.shovel",
		Icon = "icons/wm_shovel.png",
		SelectionIcon = "icons/wm_shovel_i.png",
		KillIcon = "icons/wm_shovel_k.png",
		Material = MAT_METAL,
		VModel = "models/wm/shovel/v.mdl",
		VModelPos = Vector(-6,0,1),
		VModelRot = Angle(0,-5,0),
		FOV = 80,
		WModel = "models/wm/shovel/w.mdl",
		Hold = "melee2",
		Rays = {{Angle(0,-20,0),0},{Angle(0,0,0),0.025},{Angle(0,20,0),0.025},{Angle(10,-20,0),0},{Angle(10,0,0),0.025},{Angle(10,20,0),0.025}},
		RaysDetails = 4,
		OnlyOneRay = true,
		WModelPos = Vector(4, -1, -3),
		WModelRot = Angle(180, 150, 0),
		AnimationHit = {"Attack_Quick"},
		AnimationDraw = "Draw",
		AnimationIdle = "Idle",
		AttackWait = Vector(1,-10,10),
		AttackHitWait = 0.4,
		AttackDistance = 60,
		Damage = Vector(15,30),
		DamageProp = Vector(5,20),
		PunchAngle = Angle(0,10,0),
		InertiaScale = 2,
		SwingSounds = "empty",
		BlockPos = Vector(10,0,-25),
		BlockRot = Angle(-80,-10,0),
		WBlockPos = Vector(-1,-2,0),
		WBlockRot = Angle(30,-70,0),
		BlockHold = "knife",
		BlockWait = 0.75,
		BlockPower = 0.166,
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end