AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.shield",
		Icon = "icons/wm_shield.png",
		SelectionIcon = "icons/wm_shield_i.png",
		KillIcon = "icons/wm_shield_k.png",
		Material = MAT_PLASTIC,
		VModel = "models/wm/shield/v.mdl",
		VModelPos = Vector(0,0,0),
		VModelRot = Angle(0,0,0),
		FOV = 90,
		WModel = "models/wm/shield/w.mdl",
		Hold = "melee",
		Rays = {{Angle(0,0,0),0},{Angle(-20,-10,0),0},{Angle(-20,10,0),0},{Angle(20,-10,0),0},{Angle(20,10,0),0}},
		RaysDetails = 4,
		OnlyOneRay = true,
		DontDecals = true,
		WModelPos = Vector(2.5, -5, 2),
		WModelRot = Angle(-10, -70, 0),
		AnimationHit = {"Melee"},
		AnimationDraw = "Draw",
		AnimationIdle = "Idle",
		AnimationInspect = {"Inspect"},
		AttackWait = Vector(1,-25,0),
		AttackHitWait = 0.1,
		AttackDistance = 50,
		Damage = Vector(1,5),
		DamageProp = Vector(0,1),
		IdleScale = 0.5,
		PunchAngle = Angle(10,0,0),
		BlockPos = Vector(0,0,0),
		BlockRot = Angle(0,0,0),
		WBlockPos = Vector(0,0,0),
		WBlockRot = Angle(0,0,0),
		AutoBlock = true,
		BlockWait = 0.5,
		BlockPower = 0.1,
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end