AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.screwdriver",
		Icon = "icons/wm_screwdriver.png",
		SelectionIcon = "icons/wm_screwdriver_i.png",
		KillIcon = "icons/wm_screwdriver_k.png",
		Material = MAT_METAL,
		Sharp = true,
		VModel = "models/wm/combat_knife/v.mdl",
		VModelPos = Vector(1,2,-1),
		VModelRot = Angle(0,-5,-10),
		VModelBones = {["tag_weapon"] = {Vector(0,0,0),Angle(0,0,0),Vector(0,0,0),false}},
		VModelElements = {{"models/wm/screwdriver/w.mdl","ValveBiped.Bip01_R_Hand",Vector(-12,6.75,-33),Angle(-45,0,-110),Vector(0.5,0.5,0.5)}},
		FOV = 75,
		WModel = "models/wm/screwdriver/w.mdl",
		Hold = "knife",
		Rays = {{Angle(0,0,0),0},{Angle(7,0,0),0},{Angle(-7,0,0),0},{Angle(0,0,0),0},{Angle(0,7,0),0},{Angle(0,-7,0),0}}, 
		RaysDetails = 3,
		OnlyOneRay = true,
		WModelPos = Vector(15, 27, -20),
		WModelRot = Angle(-20, -90, -90),
		WModelSize = Vector(0.5,0.5,0.5),
		AnimationHit = {"H1_Wpn_Melee_Bayonet_Knife_Stab"},
		AnimationIdle = "H1_Wpn_Melee_Bayonet_Knife_Idle",
		AnimationDraw = "H1_Wpn_Melee_Bayonet_Knife_Pullout",
		AttackWait = Vector(1,-25,0),
		AttackHitWait = 0.2,
		AttackDistance = 70,
		Damage = Vector(15,25),
		DamageProp = Vector(0,1),
		PunchAngle = Angle(1,3,0),
		InertiaScale = 0.5,
		SwingSounds = WMLib.SoundsSwing["LightSharp"],
		BlockPos = Vector(0,2,3),
		BlockRot = Angle(0,0,-30),
		WBlockPos = Vector(0,0,0),
		WBlockRot = Angle(0,0,0),
		BlockHold = "fist",
		BlockWait = 1,
		BlockPower = 0.5,
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end