AddCSLuaFile()
if WMLib then
	local Info = {
		Name = "#wm.weapon.sledge",
		Icon = "icons/wm_sledge.png",
		SelectionIcon = "icons/wm_sledge_i.png",
		KillIcon = "icons/wm_sledge_k.png",
		Heavy = true,
		Material = MAT_WOOD,
		VModel = "models/wm/sledge/v.mdl",
		VModelPos = Vector(-4,4,-1),
		VModelRot = Angle(0,-5,0),
		FOV = 80,
		WModel = "models/wm/sledge/w.mdl",
		Hold = "melee2",
		Rays = {{Angle(-40,20,0),0},{Angle(0,0,0),0.025},{Angle(40,-20,0),0.025}},
		RaysDetails = 4,
		WModelPos = Vector(3.5, -1, -3),
		WModelRot = Angle(180, 150, 5),
		AnimationHit = {"Attack_Charge_Begin"},
		AnimationHitEnd = "Attack_Charge_End",
		AnimationDraw = "Draw",
		AnimationIdle = "Idle",
		AttackWait = Vector(1,0,50),
		AttackHitWait = 0.3,
		AttackDistance = 60,
		Damage = Vector(60,80),
		DamageProp = Vector(10,30),
		KickScale = 2,
		IdleScale = 0.25,
		PunchAngle = Angle(20,-2,0),
		InertiaScale = 4,
		SwingWait = 1.1,
		BlockPos = Vector(0,0,5),
		BlockRot = Angle(0,0,-30),
		WBlockPos = Vector(0,0,2),
		WBlockRot = Angle(-45,90,-45),
		BlockHold = "knife",
		BlockWait = 0.5,
		BlockPower = 0.166,
	}
	WMLib.CreateMelee(SWEP,Info,"vanilla")
end