wm.weapon.axe=Axe
wm.weapon.baseball_bat=Baseball Bat
wm.weapon.bottle=Bottle
wm.weapon.bottle_broken=Broken Bottle
wm.weapon.cleaver=Cleaver
wm.weapon.combat_knife=Combat Knife
wm.weapon.crowbar=Crowbar
wm.weapon.fireaxe=Fireaxe
wm.weapon.fists=Fists
wm.weapon.fork=Fork
wm.weapon.fubar=Fubar
wm.weapon.hammer=Hammer
wm.weapon.ice_axe=Ice Axe
wm.weapon.katana=Katana
wm.weapon.keyboard=Keyboard
wm.weapon.kitchen_knife=Kitchen Knife
wm.weapon.mace=Mace
wm.weapon.machete=Machete
wm.weapon.modern_sword=Modern Sword
wm.weapon.pickaxe=Pickaxe
wm.weapon.pipe=Pipe
wm.weapon.pitchfork=Pitchfork
wm.weapon.police_baton=Police Baton
wm.weapon.screwdriver=Screwdriver
wm.weapon.shield=Shield
wm.weapon.shovel=Shovel
wm.weapon.sickle=Sickle
wm.weapon.sledge=Sledge
wm.weapon.soldier_shovel=Soldier Shovel
wm.weapon.stunstick=Stunstick
wm.weapon.wrench=Wrench
wm.weapon.razor=Razor
wm.weapon.rock=Rock
wm.weapon.rpg_missile=RPG Missile